<form method="post" action="index.php<?php if ($modif) {echo '?nump='.$patient['id_patient_micro'];}
										   if (isset($_GET["newpat"]) and $_GET["newpat"]==1) {echo '?newpat=1';}
										   if (isset($_GET["modpat"]) and $_GET["modpat"]==1) {echo '&modpat=1';} ?>">
	<?php
		if ($modif) {
	?>
		<input type="hidden" name="id_patient" id="id_patient"  value="<?php if ($modif) {echo $patient['id_patient_micro'];} ?>" />
	<?php
		}
	?>
		<fieldset>
		<label for="nom_patient" class="label_bd">Nom : </label><input type="text" name="nom_patient" class="donnees_bd" id="nom_patient" value="<?php if ($modif) echo $patient['nom_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["nom_patient"];} else echo '';?>" autofocus/> <label for="prenom_patient" class="label_bd">Prénom : </label><input type="text" name="prenom_patient" class="donnees_bd" id="prenom_patient" value="<?php if ($modif) echo $patient['prenom_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["prenom_patient"];} else echo '';?>" /><br /><br />
		<label for="naissance_patient" class="label_bd">Naissance : </label><input type="text" name="naissance_patient" class="donnees_bd" id="naissance_patient" value="<?php if ($modif) echo $patient['naissance_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["naissance_patient"];} else echo '';?>" /><br /><br />
		<label for="homme_patient" class="label_bd2">Homme</label> <input type="radio" name="sexe_patient" class="donnees_bd" value="homme_patient" id="homme_patient" <?php if ($modif and $patient['sex_patient_micro']=="homme_patient") echo "checked"; ?>/> | <label for="femme_patient" class="label_bd2">Femme</label> <input type="radio" name="sexe_patient" class="donnees_bd" value="femme_patient" id="femme_patient" <?php if ($modif and $patient['sex_patient_micro']=="femme_patient") echo "checked"; ?>/> | <label for="hf_patient" class="label_bd2">Je ne sais pas</label> <input type="radio" name="sexe_patient" class="donnees_bd" value="hf_patient" id="hf_patient" <?php if ($modif and $patient['sex_patient_micro']=="hf_patient") echo "checked"; ?>/><br /><br />
		<label for="adresse1_patient" class="label_bd">Adresse 1 : </label><input type="text" name="adresse1_patient" class="donnees_bd" id="adresse1_patient" value="<?php if ($modif) echo $patient['adresse1_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["adresse1_patient"];} else echo '';?>"/><br /><br />
		<label for="adresse2_patient" class="label_bd">Adresse 2 : </label><input type="text" name="adresse2_patient" class="donnees_bd" id="adresse2_patient" value="<?php if ($modif) echo $patient['adresse2_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["adresse2_patient"];} else echo '';?>"/><br /><br />
		<label for="cp_patient" class="label_bd">Code Postal : </label><input type="text" name="cp_patient" class="donnees_bd" id="cp_patient" value="<?php if ($modif) echo $patient['cp_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["cp_patient"];} else echo '';?>" /> <label for="localite_patient" class="label_bd">Localité : </label><input type="text" name="localite_patient" class="donnees_bd" id="localite_patient" value="<?php if ($modif) echo $patient['localite_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["localite_patient"];} else echo '';?>" /><br /><br />
		<label for="telephone1_patient" class="label_bd">Téléphone 1 : </label><input type="tel" name="telephone1_patient" class="donnees_bd" id="telephone1_patient" value="<?php if ($modif) echo $patient['tel1_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["telephone1_patient"];} else echo '';?>" /> <label for="telephone2_patient" class="label_bd">Téléphone 2 : </label><input type="tel" name="telephone2_patient" class="donnees_bd" id="telephone2_patient" value="<?php if ($modif) echo $patient['tel2_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["telephone2_patient"];} else echo '';?>" /><br /><br />
		<label for="mail1_patient" class="label_bd">Mail : </label><input type="email" name="mail1_patient" class="donnees_bd" id="mail1_patient" value="<?php if ($modif) echo $patient['adresse_mail_patient_micro']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["mail1_patient"];} else echo '';?>" /><br /><br />
		<label for="infos_complement" class="label_bd2">Information complémentaires : </label><textarea name="infos_complement" class="donnees_bd" id="infos_complement"><?php if ($modif) echo $patient['infos_complementaires']; elseif (isset($pas_erreur) and !$pas_erreur) {echo $_POST["infos_complement"];} else echo '';?></textarea><br /><br />
		<?php if ($modif) { ?>
			<label for="archive_patient" class="label_bd">Archives : </label><input type="checkbox" name="archive_patient" class="donnees_bd" id="archive_patient" value="1" <?php if ($modif and $patient['archive_patient_micro']==1) echo 'checked=\'checked\''; ?> /><br /><br />
		<?php } ?>
		<input type="submit" class="bouton_bd" value="<?php if ($modif) echo 'Modifier'; else echo 'Valider'; ?>" name="<?php if ($modif) echo 'Modifier'; else echo 'Valider'; ?>" id="<?php if ($modif) echo 'modifier_patient'; else echo 'creer_patient'; ?>"/> <input type="reset" class="bouton_bd" value="Annuler" name="Annuler<?php if ($modif) echo '_modif'; else echo ''; ?>_patient" id="annuler<?php if ($modif) echo '_modif'; else echo ''; ?>_patient" onclick="location.href='index.php'" />
		</fieldset>
</form>